### ISSUE TITLE
SLE_E_CONFIG error in RCF configuration 

### ISSUE THREAD

**Issue by debu97** [dariol83/ccsds#10]
Hey I am trying to implement RcF configuration for SLE. I am getting an SLE_E_CONFIG error. I am setting permitted global vcid for rcf too. how can I know due to which parameter I am getting this error?

**Comment by dariol83** [comment]
Hi @debu97 

Sorry for the late reply. I am not sure I can understand you: are you using this implementation, or are you using the ESA implementation? In my implementation, I do not use that kind of return code and the API is radically different.

Best regards,
Dario

**Comment by dariol83** [comment]
No response in one month. Closing it.

**Comment by debu97** [comment]
Hey Dariol. sorry for very late reply, got involved in some other project. I am using ESA Implementation. Have you worked with it?
