### ISSUE TITLE
Compilation failure

### ISSUE THREAD

**Issue by femtotron** [dariol83/ccsds#15]
Hello, 
I am not expert in Java but I could not launch the compilation with "mvn clean install". Everytime I have build failed error.
Can anybody explain step by step how to compile it ?

**Comment by dariol83** [comment]
Hi, I would help you gladly if you can provide some additional information. 
1) What OS are you using?
2) Is Java with version >= 11 installed correctly on your system?
3) Is Maven installed and available from the path?
4) You say that you could not launch the compilation with "mvn clean install": what kind of error does it print on the console?

Without this information, I won't be able to help you.

Best regards,
Dario

**Comment by femtotron** [comment]
Hi, 
Thank you for your return. 
I use Windows 10. 
I installed Java 19
Maven is installed too and available from the path.
I have "Build Error" problem with JAVA_HOME not defined while I did it in "environment variable" of windows

When you have availability, can we chat about that pls ??

Bests

**Comment by dariol83** [comment]
I am sorry, but I don't provide direct user support via private chat for this kind of issues (not related to the library). In any case, please do step by step the followings:
1) Download the binary version of openJDK from https://download.java.net/java/GA/jdk17.0.2/dfd4a8d0985749f896bed50d7138ee7f/8/GPL/openjdk-17.0.2_windows-x64_bin.zip
2) Decompress the archive somewhere: let's say you have it inside C:\Program Files\Java\jdk-17 (this folder contains the folders bin/, conf/, include/, and so on...)
3) Download Maven binary zip archive from https://maven.apache.org/download.cgi
4) Decompress the archive somewhere: let's say you have it inside C:\Program Files\Java\maven (this folder contains the folder bin/, boot/, and so on)
5) Open a cmd.exe terminal
6) Set the PATH env. variable: 
SET PATH=%PATH%;C:\Program Files\Java\jdk-17\bin;C:\Program Files\Java\maven\bin
7) Set the JAVA_HOME env. variable:
SET JAVA_HOME=C:\Program Files\Java\jdk-17

From this terminal, you can go inside the folder where you have the ccsds project, and run: mvn clean install.
I tried the above procedure on my Windows 10 installation and it works just fine.

Best regards,
Dario

**Comment by femtotron** [comment]
Hi Dario,
Sorry for the late reply. 
I would like to thank you for your answer which helped me to solve my problem.

Best regards.
Eren
