### ISSUE TITLE
Possibilità di un confronto :)

### ISSUE THREAD

**Issue by lifeCodingOn** [dariol83/ccsds#18]
Ciao Dario,
sono Antonio Allegretta, innanzitutto grazie per la possibilità di questo repository che hai condiviso su git, ti contatto per chiederti la possibilità di un confronto riguardo questo progetto, ti ringrazio di cuore in anticipo per la tua disponibilità. Magari puoi lasciarmi la tua email oppure puoi scegliere tu un canale di comunicazione, grazie ancora!

Cordiali saluti, keep coding :)

**Comment by dariol83** [comment]
Ciao Antonio,
Grazie per il tuo interessamento. Puoi raggiungermi mandandomi un messaggio sul mio profilo LinkedIn, che puoi raggiungere da https://www.dariolucia.eu.

Cordiali saluti a te,
Dario
