### ISSUE TITLE
Many objects in the library are not implementing Serializable

### ISSUE THREAD

**Issue by slux83** [dariol83/ccsds#6]
As per title.

```Caused by: java.io.NotSerializableException: eu.dariolucia.ccsds.tmtc.datalink.pdu.TmTransferFrame```

Another example is the ```eu.dariolucia.ccsds.tmtc.transport.pdu.SpacePacket``` class that also would require some helper method to handle the annotations.

**Comment by slux83** [comment]
Attached the patch that adds some "Serializable" to the data structures that could be potentially passed remotely by a 3rd party system.

[issue_6.patch.txt](https://github.com/dariol83/ccsds/files/5764664/issue_6.patch.txt)

**Comment by dariol83** [comment]
Fixed in 0.3.4, fix backported to master.
